/*
Copyright 2026 Chainguard, Inc.
SPDX-License-Identifier: Apache-2.0
*/

package component

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"testing"
	"testing/fstest"
)

// makeJar builds a jar carrying Maven metadata for each coordinate given, which
// is how a shaded jar records the dependencies folded into it.
func makeJar(t *testing.T, coords ...[3]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	add := func(name, body string) {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatalf("zip create %s: %v", name, err)
		}
		if _, err := io.WriteString(w, body); err != nil {
			t.Fatalf("zip write %s: %v", name, err)
		}
	}
	add("META-INF/MANIFEST.MF", "Manifest-Version: 1.0\n")
	for _, c := range coords {
		add(fmt.Sprintf("META-INF/maven/%s/%s/pom.properties", c[0], c[1]),
			fmt.Sprintf("#Generated by Maven\ngroupId=%s\nartifactId=%s\nversion=%s\n", c[0], c[1], c[2]))
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("zip close: %v", err)
	}
	return buf.Bytes()
}

func TestEnumerateJavaComponents(t *testing.T) {
	tree := Tree{
		Name: "melange-out/app",
		FS: fstest.MapFS{
			"usr/lib/app/libs/commons-beanutils-1.11.0.jar": {
				Data: makeJar(t, [3]string{"commons-beanutils", "commons-beanutils", "1.11.0"}),
			},
			"usr/lib/app/libs/jackson-core-2.19.0.jar": {
				Data: makeJar(t, [3]string{"com.fasterxml.jackson.core", "jackson-core", "2.19.0"}),
			},
			"usr/lib/app/libs/app.jar": {Data: makeJar(t)}, // Gradle-built: no Maven metadata.
			"usr/lib/app/config.txt":   {Data: []byte("not a jar")},
		},
	}

	enumerated := enumerateJava(t.Context(), []Tree{tree}, "app")
	comps := enumerated.Components
	got := byPURL(comps)
	if len(comps) != 2 {
		t.Fatalf("components: got = %d (%v), want = 2", len(comps), comps)
	}

	// The groupId is the purl namespace and the artifactId is its name.
	c, ok := got["pkg:maven/com.fasterxml.jackson.core/jackson-core@2.19.0"]
	if !ok {
		t.Fatalf("missing the jackson component; got %v", comps)
	}
	if c.Name != "com.fasterxml.jackson.core:jackson-core" || c.Version != "2.19.0" {
		t.Errorf("coordinates: got = %q@%q, want = com.fasterxml.jackson.core:jackson-core@2.19.0", c.Name, c.Version)
	}
	if c.Ecosystem != "maven" || c.Kind != KindEcosystem {
		t.Errorf("got ecosystem/kind = %q/%q, want maven/%s", c.Ecosystem, c.Kind, KindEcosystem)
	}
	if c.DiscoveredFrom != "melange-out/app/usr/lib/app/libs/jackson-core-2.19.0.jar" {
		t.Errorf("discovered_from: got = %q, want the jar it was read from", c.DiscoveredFrom)
	}

	// A jar without coordinates is reported as a failure, not silently
	// dropped: it is either the package's own Gradle-built output or a genuine
	// coverage gap, and a consumer has to be able to tell that something
	// shipped without being enumerated.
	if !hasFailureContaining(enumerated.Failures, "carry no Maven coordinates") {
		t.Errorf("failures: got = %v, want the unidentified jars recorded", enumerated.Failures)
	}
}

// TestEnumerateJavaComponentsUnpacksShadedJars covers the uber-jar shape: kafka
// ships one jar holding thirteen jline components, and every one of them
// genuinely ships.
func TestEnumerateJavaComponentsUnpacksShadedJars(t *testing.T) {
	tree := Tree{
		Name: "melange-out/app",
		FS: fstest.MapFS{
			"libs/jline-3.30.4.jar": {Data: makeJar(t,
				[3]string{"org.jline", "jline", "3.30.4"},
				[3]string{"org.jline", "jline-reader", "3.30.4"},
				[3]string{"org.jline", "jline-terminal", "3.30.4"},
			)},
		},
	}
	comps, _ := split(enumerateJava(t.Context(), []Tree{tree}, "app"))
	if len(comps) != 3 {
		t.Fatalf("components: got = %d (%v), want = 3, one per bundled coordinate", len(comps), comps)
	}
	for _, want := range []string{
		"pkg:maven/org.jline/jline@3.30.4",
		"pkg:maven/org.jline/jline-reader@3.30.4",
		"pkg:maven/org.jline/jline-terminal@3.30.4",
	} {
		if _, ok := byPURL(comps)[want]; !ok {
			t.Errorf("missing %s from the shaded jar", want)
		}
	}
}

func TestEnumerateJavaComponentsIgnoresUnreadableJars(t *testing.T) {
	tree := Tree{
		Name: "melange-out/app",
		FS: fstest.MapFS{
			"libs/truncated.jar": {Data: []byte("PK\x03\x04 not really a zip")},
			"libs/good.jar":      {Data: makeJar(t, [3]string{"g", "a", "1.0"})},
		},
	}
	enumerated := enumerateJava(t.Context(), []Tree{tree}, "app")
	if got := enumerated.Components; len(got) != 1 || got[0].PURL != "pkg:maven/g/a@1.0" {
		t.Errorf("components: got = %v, want only the readable jar", got)
	}
	if !hasFailureContaining(enumerated.Failures, "carry no Maven coordinates") {
		t.Errorf("failures: got = %v, want the unreadable jar counted", enumerated.Failures)
	}
}

func TestReadPomProperties(t *testing.T) {
	for _, tt := range []struct {
		name string
		body string
		want gav
		ok   bool
	}{{
		name: "complete",
		body: "#Generated by Maven\n#Sun May 25 13:14:00 UTC 2025\ngroupId=org.example\nartifactId=widget\nversion=2.1\n",
		want: gav{"org.example", "widget", "2.1"},
		ok:   true,
	}, {
		name: "missing version is not a coordinate",
		body: "groupId=org.example\nartifactId=widget\n",
		ok:   false,
	}, {
		name: "comments and blanks only",
		body: "#Generated by Maven\n\n",
		ok:   false,
	}} {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := readPomProperties(bytes.NewReader([]byte(tt.body)))
			if ok != tt.ok {
				t.Fatalf("ok: got = %v, want = %v", ok, tt.ok)
			}
			if ok && got != tt.want {
				t.Errorf("got = %+v, want = %+v", got, tt.want)
			}
		})
	}
}

func TestMavenPURL(t *testing.T) {
	if got := MavenPURL("org.example", "widget", "2.1"); got != "pkg:maven/org.example/widget@2.1" {
		t.Errorf("got = %q", got)
	}
	if got := MavenPURL("org.example", "widget", ""); got != "pkg:maven/org.example/widget" {
		t.Errorf("versionless: got = %q", got)
	}
}
