/*
Copyright 2026 Chainguard, Inc.
SPDX-License-Identifier: Apache-2.0
*/

package component

import (
	"cmp"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io/fs"
	"path"
	"regexp"
	"slices"
	"strings"

	"github.com/BurntSushi/toml"
)

// manifestFileNames are the ecosystem manifests worth reading, mapped to the
// ecosystem whose format they are.
//
// go.mod is listed and has no reader, because Go has no license field anywhere
// in its metadata. It earns its place by being a manifest worth retaining when
// an artifact is expanded, which is what IsManifestFile answers.
//
// Python core metadata is listed separately in PyPIMetadataFiles: it is
// generated by the build rather than hand-written, but it is where a published
// sdist or wheel states its license, so it is read on the same terms.
var manifestFileNames = map[string]Ecosystem{
	"package.json":   EcosystemNpm,
	"Cargo.toml":     EcosystemCargo,
	"pyproject.toml": EcosystemPyPI,
	"setup.cfg":      EcosystemPyPI,
	"pom.xml":        EcosystemMaven,
	"go.mod":         EcosystemGo,
}

// IsManifestFile reports whether a name is an ecosystem manifest that may
// declare a license. It is exported because a caller deciding what to retain
// from a fetched artifact needs the same rule that reads a source tree.
func IsManifestFile(name string) bool {
	if _, ok := manifestFileNames[name]; ok {
		return true
	}
	if slices.Contains(PyPIMetadataFiles, name) {
		return true
	}
	return isParentPOM(name)
}

// Manifest is an author-declared license field, read out of a component's own
// manifest.
//
// It is a declaration, never a conclusion: it records what a component's
// authors claim, faithfully, including when the claim disagrees with the
// license files they shipped. That disagreement is a finding in its own right,
// which it cannot be if the two are conflated.
type Manifest struct {
	// Path is where the declaration was read from, relative to the component
	// root.
	Path string `json:"path"`
	// Ecosystem names the manifest's format.
	Ecosystem Ecosystem `json:"ecosystem"`
	// License is the declared value exactly as written. Run spdx.Canonicalize
	// before comparing it with anything: most of these are not valid SPDX.
	License string `json:"license"`
	// LicenseFile is the path a manifest named in place of a license, relative
	// to the component root, and is set only when License is empty.
	//
	// It is a separate field rather than a value in License because pointing at
	// a file is not declaring a license: the two answer different questions, and
	// a consumer has to be able to tell that this component declared nothing
	// machine-readable. Encoding it as an identifier would also put a filename
	// into the LicenseRef- namespace, which names license texts by digest and is
	// what curation entries are keyed on.
	LicenseFile string `json:"license_file,omitempty"`
}

// Manifests reads the license fields declared by the manifests at the root of
// fsys.
//
// Only the root is read. A manifest in a subdirectory declares the licensing of
// that subdirectory, which is a component of its own if it is anything at all.
func Manifests(fsys fs.FS) []Manifest {
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return nil
	}
	var out []Manifest
	for _, e := range entries {
		if e.IsDir() || !IsManifestFile(e.Name()) {
			continue
		}
		if m, ok := readManifest(fsys, e.Name()); ok {
			out = append(out, m)
		}
	}
	return out
}

// DeclaredLicense reports the license a component declares in its own manifest,
// reading the location that ecosystem treats as authoritative.
//
// This is upstream's claim, not a determination: it is recorded as the declared
// license and it can settle an otherwise ambiguous multi-license component, but
// it never substitutes for classifying the content. Ecosystems differ in whether
// they have such a field at all - Go has none anywhere, which is exactly why Go
// dependencies are unlicensed everywhere today.
func DeclaredLicense(fsys fs.FS, ecosystem Ecosystem) string {
	switch ecosystem {
	case EcosystemCargo:
		if m, ok := readManifest(fsys, "Cargo.toml"); ok {
			return m.License
		}
	case EcosystemNpm:
		if m, ok := readManifest(fsys, "package.json"); ok {
			return m.License
		}
	case EcosystemPyPI:
		return declaredPyPI(fsys)
	case EcosystemMaven:
		return declaredMaven(fsys)
	}
	return ""
}

// readManifest dispatches to the reader for one manifest file.
func readManifest(fsys fs.FS, name string) (Manifest, bool) {
	var license, licenseFile string
	switch {
	case name == "package.json":
		license = jsonManifestLicense(fsys, name)
	case name == "Cargo.toml":
		license, licenseFile = cargoManifestLicense(fsys, name)
	case name == "pyproject.toml":
		license, licenseFile = pyprojectLicense(fsys, name)
	case name == "setup.cfg":
		license = setupCfgLicense(fsys, name)
	case slices.Contains(PyPIMetadataFiles, name):
		license = pyMetadataLicense(fsys, name)
	case name == "pom.xml" || isParentPOM(name):
		license = pomLicense(fsys, name)
	}
	if license == "" && licenseFile == "" {
		return Manifest{}, false
	}
	ecosystem := manifestFileNames[name]
	if ecosystem == "" {
		switch {
		case slices.Contains(PyPIMetadataFiles, name):
			ecosystem = EcosystemPyPI
		case isParentPOM(name):
			ecosystem = EcosystemMaven
		}
	}
	return Manifest{Path: name, Ecosystem: ecosystem, License: license, LicenseFile: licenseFile}, true
}

// jsonManifestLicense reads the license out of a package.json.
//
// npm requires the license field to be an SPDX expression, so the modern form
// needs no interpretation. The deprecated forms do: a "licenses" array of
// objects predates the requirement, and its entries were a choice, so they
// compose with OR the way Maven's do.
func jsonManifestLicense(fsys fs.FS, name string) string {
	data, err := readBounded(fsys, name, maxManifestBytes)
	if err != nil {
		return ""
	}
	var doc struct {
		License  json.RawMessage `json:"license"`
		Licenses json.RawMessage `json:"licenses"`
	}
	if json.Unmarshal(data, &doc) != nil {
		return ""
	}
	if license := jsonLicenseField(doc.License); license != "" {
		return license
	}
	return jsonLicenseField(doc.Licenses)
}

// jsonLicenseField normalizes the shapes the field has been written in: a
// string, an array of strings, an object with a type, or an array of those.
func jsonLicenseField(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var one string
	if json.Unmarshal(raw, &one) == nil {
		return strings.TrimSpace(one)
	}
	var many []string
	if json.Unmarshal(raw, &many) == nil {
		return joinChoice(many)
	}
	var typed struct {
		Type string `json:"type"`
		URL  string `json:"url"`
	}
	if json.Unmarshal(raw, &typed) == nil && (typed.Type != "" || typed.URL != "") {
		return cmp.Or(strings.TrimSpace(typed.Type), strings.TrimSpace(typed.URL))
	}
	var typedMany []struct {
		Type string `json:"type"`
		URL  string `json:"url"`
	}
	if json.Unmarshal(raw, &typedMany) == nil {
		named := make([]string, 0, len(typedMany))
		for _, l := range typedMany {
			named = append(named, cmp.Or(strings.TrimSpace(l.Type), strings.TrimSpace(l.URL)))
		}
		return joinChoice(named)
	}
	return ""
}

// cargoManifestLicense reads the license field from a crate's Cargo.toml,
// returning the declared license or, failing that, the file the crate named
// instead.
//
// A crate that points at a bundled license file declares nothing
// machine-readable. The pointer is still worth recording - the file itself is
// classified along with the rest of the content - but it is returned as a path
// rather than a license, so that a caller comparing declared against detected
// cannot read a filename as an identifier.
func cargoManifestLicense(fsys fs.FS, name string) (license, licenseFile string) {
	data, err := readBounded(fsys, name, maxManifestBytes)
	if err != nil {
		return "", ""
	}
	var doc struct {
		Package struct {
			License     string `toml:"license"`
			LicenseFile string `toml:"license-file"`
		} `toml:"package"`
	}
	if toml.Unmarshal(data, &doc) != nil {
		return "", ""
	}
	if declared := strings.TrimSpace(doc.Package.License); declared != "" {
		return declared, ""
	}
	return "", strings.TrimSpace(doc.Package.LicenseFile)
}

// pyprojectLicense reads the license out of a pyproject.toml, covering both the
// PEP 621 project table and poetry's own. Like Cargo, PEP 621 allows a file in
// place of an expression, which is returned separately for the same reason.
func pyprojectLicense(fsys fs.FS, name string) (license, licenseFile string) {
	data, err := readBounded(fsys, name, maxManifestBytes)
	if err != nil {
		return "", ""
	}
	var doc map[string]any
	if toml.Unmarshal(data, &doc) != nil {
		return "", ""
	}
	if project, ok := doc["project"].(map[string]any); ok {
		switch declared := project["license"].(type) {
		case string:
			if declared != "" {
				return declared, ""
			}
		case map[string]any:
			if text, ok := declared["text"].(string); ok && text != "" {
				return text, ""
			}
			if file, ok := declared["file"].(string); ok && file != "" {
				return "", strings.TrimSpace(file)
			}
		}
	}
	if tool, ok := doc["tool"].(map[string]any); ok {
		if poetry, ok := tool["poetry"].(map[string]any); ok {
			if declared, ok := poetry["license"].(string); ok && declared != "" {
				return declared, ""
			}
		}
	}
	return "", ""
}

var setupCfgLicenseRe = regexp.MustCompile(`(?mi)^\s*license(?:_expression)?\s*=\s*(.+?)\s*$`)

// setupCfgLicense reads the license out of a setup.cfg.
func setupCfgLicense(fsys fs.FS, name string) string {
	data, err := readBounded(fsys, name, maxManifestBytes)
	if err != nil {
		return ""
	}
	m := setupCfgLicenseRe.FindSubmatch(data)
	if m == nil {
		return ""
	}
	license := strings.TrimSpace(string(m[1]))
	if license == "" || strings.HasPrefix(license, "file:") {
		return ""
	}
	return license
}

// pyMetadataLicense reads the license out of Python core metadata.
func pyMetadataLicense(fsys fs.FS, name string) string {
	headers, err := ReadPyPIMetadata(fsys, name)
	if err != nil {
		return ""
	}
	return PyPIMetadataLicense(headers)
}

// declaredPyPI reads the license a Python distribution declares, from wherever
// the archive it arrived in keeps its core metadata: PKG-INFO at the root of an
// sdist, METADATA under .dist-info in a wheel.
func declaredPyPI(fsys fs.FS) string {
	for _, p := range pyMetadataPaths(fsys) {
		if license := pyMetadataLicense(fsys, p); license != "" {
			return license
		}
	}
	return ""
}

// pyMetadataPaths lists where core metadata can be, nearest first.
func pyMetadataPaths(fsys fs.FS) []string {
	paths := []string{"PKG-INFO", "METADATA"}
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return paths
	}
	for _, e := range entries {
		if e.IsDir() && strings.HasSuffix(e.Name(), distInfoSuffix) {
			paths = append(paths, path.Join(e.Name(), "METADATA"))
		}
	}
	return paths
}

// MaxPOMAncestry bounds how far a POM's parent chain is followed. Maven
// inheritance is a handful of levels in practice; the bound exists so a cyclic
// or hostile chain cannot make one component's resolution unbounded.
const MaxPOMAncestry = 8

// POMName is where a POM sits in a component's filesystem. The component's own
// POM keeps the conventional name so the manifest rules recognize it, and
// ancestors are numbered by distance.
//
// It is exported so that whatever fetches a parent chain writes the names this
// package reads: the two would otherwise agree only by coincidence.
func POMName(depth int) string {
	if depth == 0 {
		return "pom.xml"
	}
	return fmt.Sprintf("pom-parent-%d.xml", depth)
}

// isParentPOM reports whether a name is an inherited POM written by POMName.
func isParentPOM(name string) bool {
	for depth := 1; depth < MaxPOMAncestry; depth++ {
		if name == POMName(depth) {
			return true
		}
	}
	return false
}

// declaredMaven reads the license a Java artifact declares in its POM.
//
// The nearest POM that declares anything wins. Most POMs declare nothing
// themselves and inherit from a parent: of the 65 POMs in a representative
// package, 29 declare licenses directly and 36 declare them only through a
// parent, so walking the chain is most of the coverage rather than a refinement
// of it. Nearest to furthest is Maven's own precedence.
func declaredMaven(fsys fs.FS) string {
	for depth := range MaxPOMAncestry {
		if license := pomLicense(fsys, POMName(depth)); license != "" {
			return license
		}
	}
	return ""
}

// pomLicense renders a POM's licenses block as an expression.
//
// Maven's reference states that several license entries mean the consumer may
// pick any one of them, so they compose with OR. That is the opposite of the
// usual default, and getting it backwards would report an obligation nobody
// has.
//
// A license entry names itself, links to itself, or both. The name is preferred
// because that is what an identifier is usually written as, but a URL is a real
// signal too: SPDX records the canonical URL of every license it lists, so a
// bare link still resolves.
func pomLicense(fsys fs.FS, name string) string {
	data, err := readBounded(fsys, name, maxManifestBytes)
	if err != nil {
		return ""
	}
	var doc struct {
		Licenses struct {
			License []struct {
				Name string `xml:"name"`
				URL  string `xml:"url"`
			} `xml:"license"`
		} `xml:"licenses"`
	}
	if xml.Unmarshal(data, &doc) != nil {
		return ""
	}
	var named []string
	for _, l := range doc.Licenses.License {
		if v := cmp.Or(strings.TrimSpace(l.Name), strings.TrimSpace(l.URL)); v != "" {
			named = append(named, v)
		}
	}
	return joinChoice(named)
}

// joinChoice renders several alternatives as an SPDX choice, dropping blanks.
func joinChoice(values []string) string {
	kept := make([]string, 0, len(values))
	for _, v := range values {
		if v = strings.TrimSpace(v); v != "" {
			kept = append(kept, v)
		}
	}
	return strings.Join(kept, " OR ")
}
